--liquibase formatted sql

--changeset vitor:1

DROP SCHEMA IF EXISTS DUNGEONSANDDRAGONS;
CREATE SCHEMA DUNGEONSANDDRAGONS;
USE DUNGEONSANDDRAGONS;

--rollback DROP SCHEMA DUNGEONSANDDRAGONS;

--changeset vitor:2

DROP TABLE IF EXISTS USU_USUARIO;
CREATE TABLE USU_USUARIO(
    USU_ID BIGINT UNSIGNED AUTO_INCREMENT,
    USU_NOME_USUARIO VARCHAR(50) NOT NULL,
    USU_SENHA VARCHAR(50) NOT NULL,
    USU_NOME_EXIBICAO VARCHAR(64),
    USU_ADMINISTRADOR VARCHAR(20),
    ADM_CLASSIFICACAO INT,

    CONSTRAINT PK_USU_ID PRIMARY KEY (USU_ID),
    CONSTRAINT UK_USU_NOME_USUARIO UNIQUE (USU_NOME_USUARIO)
);

--rollback drop table USU_USUARIO;

--changeset vitor:3

DROP TABLE IF EXISTS PER_PERSONAGEM;
CREATE TABLE PER_PERSONAGEM(
    PER_ID BIGINT UNSIGNED AUTO_INCREMENT,
    PER_PROPRIETARIO BIGINT UNSIGNED,
    PER_NOME VARCHAR(50) NOT NULL,
    PER_RACA VARCHAR(20) NOT NULL,
    PER_CLASSE VARCHAR(50) NOT NULL,
	PER_NIVEL BIGINT UNSIGNED,
	PER_ANTECEDENTE VARCHAR(50),
	PER_FORCA BIGINT UNSIGNED,
	PER_DESTREZA BIGINT UNSIGNED,
	PER_CONSTITUICAO BIGINT UNSIGNED,
	PER_INTELIGENCIA BIGINT UNSIGNED,
	PER_SABEDORIA BIGINT UNSIGNED,
	PER_CARISMA BIGINT UNSIGNED,

    CONSTRAINT PK_PERSONAGEM PRIMARY KEY (PER_ID, PER_PROPRIETARIO),
    CONSTRAINT FK_PER_USU FOREIGN KEY (PER_PROPRIETARIO)
        REFERENCES USU_USUARIO (USU_ID)
);

--rollback drop table PER_PERSONAGEM;

--changeset vitor:4

DROP TABLE IF EXISTS FEI_FEITICEIRO;
CREATE TABLE FEI_FEITICEIRO(
    FEI_ID BIGINT UNSIGNED,
    FEI_MAGIAS_CONHECIDAS INT,
    FEI_MODIFICADOR_HABILIDADE INT,

    CONSTRAINT PK_FEI_ID PRIMARY KEY (FEI_ID),
    CONSTRAINT FK_FEI_USU FOREIGN KEY (FEI_ID)
        REFERENCES PER_PERSONAGEM (PER_ID)
);

--rollback drop table FEI_FEITICEIRO;

--changeset railson:5

DROP TABLE IF EXISTS LUT_LUTADOR;
CREATE TABLE LUT_LUTADOR(
    LUT_ID BIGINT UNSIGNED,
    LUT_DADOS_SUPERIORIDADE INT,

    CONSTRAINT PK_LUT_ID PRIMARY KEY (LUT_ID),
    CONSTRAINT FK_LUT_USU FOREIGN KEY (LUT_ID)
        REFERENCES PER_PERSONAGEM (PER_ID)
);

--rollback drop table LUT_LUTADOR;

--changeset railson:6

DROP TABLE IF EXISTS GRU_GRUPO;
CREATE TABLE GRU_GRUPO(
    GRU_ID BIGINT UNSIGNED AUTO_INCREMENT,
    GRU_MESTRE BIGINT UNSIGNED,
    GRU_NOME VARCHAR(50),

    CONSTRAINT PK_GRUPO PRIMARY KEY (GRU_ID, GRU_MESTRE),
    CONSTRAINT UK_GRUPO UNIQUE (GRU_MESTRE, GRU_NOME),
    CONSTRAINT FK_GRU_PER FOREIGN KEY (GRU_MESTRE)
        REFERENCES USU_USUARIO (USU_ID)
);

--rollback drop table GRU_GRUPO;

--changeset railson:7

DROP TABLE IF EXISTS INT_INTEGRANTE;
CREATE TABLE INT_INTEGRANTE(
    GRU_ID BIGINT UNSIGNED,
    PER_ID BIGINT UNSIGNED,

    CONSTRAINT PK_INTEGRANTE PRIMARY KEY (GRU_ID, PER_ID),
    CONSTRAINT FK_INT_GRU FOREIGN KEY (GRU_ID)
        REFERENCES GRU_GRUPO (GRU_ID),
    CONSTRAINT FK_INT_PER FOREIGN KEY (PER_ID)
        REFERENCES PER_PERSONAGEM (PER_ID)
);

--rollback drop table INT_INTEGRANTE;

--changeset railson:8

INSERT INTO dungeonsanddragons.usu_usuario
(usu_id,
usu_nome_exibicao,
usu_nome_usuario,
usu_senha,
adm_classificacao)
VALUES
(1,
'Railson',
'Tales',
'123',
1);

-- rollback delete from usu_usuario where usu_id = 1;
